### ISSUE TITLE
Error when updating the packaging.

### ISSUE THREAD

**Issue by mdsdtech** [sbwml/kmod-x86_64#1]
Openwrt from: https://x86.cooluc.com/releases/openwrt-23.05/v23.05.2

![Screenshot from 2024-01-04 00-15-18](https://github.com/sbwml/kmod-x86_64/assets/70020155/922af4e5-018a-4d28-a858-d35729bee554)

**Comment by sbwml** [comment]
raw.cooluc.com has been terminated by replit.  Until this issue is resolved, you can edit the installation source by replacing the openwrt_core line with the following 

`src/gz openwrt_core https://raw.githubusercontent.com/sbwml/kmod-x86_64/main/6.6.9-1-7d1c8d5ad69afb5a0233ade13320b010`

**Comment by mdsdtech** [comment]
Thank you for the solution.
